Repository MaiQuocHuy/reactjs-course-project, pull requests merged in 2025-09, with the labels that each got.

#32 feat: Done notification fearture
  src/components/admin/AdminLayout.tsx
  src/components/notifications/NotificationTrigger.tsx
  src/components/notifications/NotificationsModal.tsx
  src/components/ui/custom-pagination.tsx
  src/services/notificationsApi.ts
  src/store/store.ts
  src/types/certificates/index.ts
  src/types/notifications/index.ts
Labels: Review effort 3/5

#33 Thaison
  src/components/discounts/CreateDiscountDialog.tsx
  src/components/discounts/DiscountTable.tsx
  src/components/discounts/DiscountTableSkeleton.tsx
  src/components/discounts/SendEmailDialog/AdvanceSearchBar.tsx
  src/components/discounts/SendEmailDialog/EmailSubject.tsx
  src/components/discounts/SendEmailDialog/SelectedUsersList.tsx
  src/components/discounts/SendEmailDialog/UserInfo.tsx
  src/components/discounts/WarningAlert.tsx
  src/pages/discounts/DiscountsPage.tsx
  src/types/discounts/index.ts
Labels: Review effort 3/5

#34 Using Link to view student details
  src/components/discounts/SendEmailDialog/AdvanceSearchBar.tsx
  src/components/discounts/SendEmailDialog/SelectedUsersList.tsx
Labels: Review effort 2/5

#38 Dont Admin Revenue Management
  src/App.tsx
  src/components/Dashboard/StatPayments.tsx
  src/components/Dashboard/StatRevenues.tsx
  src/components/Dashboard/StatStudents.tsx
  src/components/Dashboard/SystemStatus.tsx
  src/components/admin/AdminLayout.tsx
  src/components/revenues/ComparativeAnalysis.tsx
  src/components/revenues/MonthlyRevenue/DailyRevenueCard.tsx
  src/components/revenues/MonthlyRevenue/MonthlyRevenue.tsx
  src/components/revenues/MonthlyRevenue/MonthlyRevenueChart.tsx
  src/components/revenues/MonthlyRevenue/MonthlyRevenueHeader.tsx
  src/components/revenues/PerformanceMetrics/CategoryDistributionPie.tsx
  src/components/revenues/PerformanceMetrics/CategoryRevenueChart.tsx
  src/components/revenues/PerformanceMetrics/PerformanceMetrics.tsx
  src/components/revenues/RevenueContext.tsx
  src/components/revenues/SeasonalHeatmap.tsx
  src/components/revenues/Statistics.tsx
  src/components/revenues/TopSpendersCard.tsx
  src/components/revenues/index.ts
  src/components/revenues/revenueUtils.ts
  src/data/revenuesMockData.ts
  src/pages/Dashboard/DashboardPage.tsx
  src/pages/admin/DashboardPage.tsx
  src/pages/admin/courses/course-detail/InstructorInfoPage.tsx
  src/pages/revenues/RevenuesPage.tsx
  src/services/mockRevenueApi.ts
  src/services/revenuesApi.ts
  src/store/store.ts
  src/types/revenues/comparativeAnalysis.ts
  src/types/revenues/index.ts
  src/types/revenues/monthlyRevenue.ts
  src/types/revenues/performanceMetrics.ts
  src/types/revenues/seasonalHeatmap.ts
  src/types/revenues/statistics.ts
  src/types/revenues/topSpenders.ts
Labels: Review effort 4/5
